import { execSync } from 'child_process';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';
import { readFileSync, writeFileSync } from 'fs';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const projectRoot = join(__dirname, '..');

console.log('📦 Installation du CLI Supabase...');
try {
  // Vérifier si supabase est installé
  execSync('npx supabase --version', { stdio: 'pipe' });
  console.log('✅ CLI Supabase déjà installé');
} catch (error) {
  console.log('🔧 Installation du CLI Supabase...');
  execSync('npm install @supabase/cli --no-save', { stdio: 'inherit', cwd: projectRoot });
}

console.log('🔄 Génération des types TypeScript depuis Supabase...');
try {
  const command = `npx supabase gen types typescript --project-id vsuzocbkolhnzcoxdhji --schema public`;
  const types = execSync(command, { encoding: 'utf8', cwd: projectRoot });
  
  const outputPath = join(projectRoot, 'src/lib/database.types.ts');
  writeFileSync(outputPath, types);
  
  console.log(`✅ Types générés avec succès !`);
  console.log(`📁 Fichier: ${outputPath}`);
  
  // Ajouter un commentaire en haut du fichier
  const fileContent = `// Generated by Supabase CLI\n// Date: ${new Date().toISOString()}\n\n${types}`;
  writeFileSync(outputPath, fileContent);
  
} catch (error) {
  console.error('❌ Erreur lors de la génération des types:', error.message);
  
  // Créer un fichier de types basique en attendant
  console.log('🔄 Création de types basiques...');
  const basicTypes = `// Types basiques - À remplacer par la génération automatique
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  public: {
    Tables: {
      // Les types seront générés automatiquement
    };
    Views: {};
    Functions: {};
    Enums: {};
  };
};
`;
  
  const outputPath = join(projectRoot, 'src/lib/database.types.ts');
  writeFileSync(outputPath, basicTypes);
  console.log(`📁 Fichier basique créé: ${outputPath}`);
}